### ISSUE TITLE
Serious problem when timeout.

### ISSUE THREAD

**Issue by PetruCazac** [PetruCazac/Webserv#57]
When there is a low timeout, the server would close the socket, close the socket map  but still send the answer from the CGI script. Further accessing the files on the server is impossible. Site crashes. Test done with a keepalive_timeout 10 and send timeout 10. CGI script would wait for 10 sec and send back a message.

**Comment by leonfabi** [comment]
@PetruCazac 
It send now an error page if the client times out during an cgi execution. And the child process is killed.
